const germanyStates: any = [
  { label: 'Germany', value: 'DE' },
  { label: 'Baden-Württemberg', value: 'DE-BW' },
  { label: 'Bavaria', value: 'DE-BY' },
  { label: 'Berlin', value: 'DE-BE' },
  { label: 'Brandenburg', value: 'DE-BB' },
  { label: 'Bremen', value: 'DE-HB' },
  { label: 'Hamburg', value: 'DE-HH' },
  { label: 'Hesse', value: 'DE-HE' },
  { label: 'Mecklenburg-Vorpommern', value: 'DE-MV' },
  { label: 'Lower Saxony', value: 'DE-NI' },
  { label: 'North Rhine-Westphalia', value: 'DE-NW' },
  { label: 'Rhineland-Palatinate', value: 'DE-RP' },
  { label: 'Saarland', value: 'DE-SL' },
  { label: 'Saxony', value: 'DE-SN' },
  { label: 'Saxony-Anhalt', value: 'DE-ST' },
  { label: 'Schleswig-Holstein', value: 'DE-SH' },
  { label: 'Thuringia', value: 'DE-TH' },
  // OR
  { name: "Baden-Württemberg", code: "DE-BW" },
  { name: "Bayern", code: "DE-BY" },
  { name: "Berlin", code: "DE-BE" },
  { name: "Brandenburg", code: "DE-BB" },
  { name: "Bremen", code: "DE-HB" },
  { name: "Hamburg", code: "DE-HH" },
  { name: "Hessen", code: "DE-HE" },
  { name: "Mecklenburg-Vorpommern", code: "DE-MV" },
  { name: "Niedersachsen", code: "DE-NI" },
  { name: "Nordrhein-Westfalen", code: "DE-NW" },
  { name: "Rheinland-Pfalz", code: "DE-RP" },
  { name: "Saarland", code: "DE-SL" },
  { name: "Sachsen", code: "DE-SN" },
  { name: "Sachsen-Anhalt", code: "DE-ST" },
  { name: "Schleswig-Holstein", code: "DE-SH" },
  { name: "Thüringen", code: "DE-TH" },
];

export default germanyStates;